export type PublicLanguage = "uz" | "en" | "ru";

export function readLanguage(value: unknown): PublicLanguage {
  return value === "en" || value === "ru" ? value : "uz";
}

export function publicHref(path: string, language: PublicLanguage) {
  if (language === "uz") return path;
  const [pathname, hash] = path.split("#");
  return pathname + (pathname.includes("?") ? "&" : "?") + "lang=" + language + (hash ? "#" + hash : "");
}

const uz = {
  language: "Tilni tanlash", courses: "Kurslar", how: "Qanday ishlaydi", login: "Kirish", back: "Kirishga qaytish", home: "Bosh sahifa",
  eyebrow: "YANGI IMKONIYATLAR SARI", heroStart: "Bilimingizni", heroGold: "keyingi bosqichga", heroEnd: "olib chiqing.",
  heroDescription: "Zamonaviy kasblar uchun amaliy bilimlar, real loyihalar va o‘lchanadigan natijalar. Gradexa bilan rivojlanish yo‘lingiz aniqroq bo‘ladi.",
  start: "O‘qishni boshlash", viewCourses: "Kurslarni ko‘rish", video: "Video darslar", videoDescription: "Tushunarli va amaliy", tests: "Amaliy testlar", testsDescription: "Bilimni mustahkamlang", results: "Natijalar", resultsDescription: "Rivojlanishingizni kuzating",
  quote: "Kichik qadamlar katta natijalarga olib keladi.", goal: "Maqsad sari", goalDescription: "Har kuni bir qadam", popular: "Ommabop kurslar", allCourses: "Barcha kurslarni ko‘rish",
  frontendDescription: "Zamonaviy veb interfeyslar yaratish asoslarini o‘rganing.", jsDescription: "JavaScript’ni noldan amaliy loyihalargacha o‘zlashtiring.", uiDescription: "Zamonaviy dizayn tizimlari va komponentlar bilan ishlash.",
  frontendCategory: "Frontend", jsCategory: "Dasturlash", uiCategory: "Dizayn", beginner: "Boshlang‘ich", intermediate: "O‘rta", learners: "nafar o‘quvchi", openCourse: "Kursni ochish",
  fourSteps: "4 oddiy qadamda yangi bilimga", step1: "Kursni tanlang", step1Description: "Maqsadingizga mos kursni tanlab oling.", step2: "Darslarni o‘rganing", step2Description: "Video darslar orqali bosqichma-bosqich.", step3: "Amaliy testlardan o‘ting", step3Description: "Bilimingizni amalda sinab ko‘ring.", step4: "Natijaga erishing", step4Description: "Yangi ko‘nikmalar bilan oldinga boring.",
  knowledge: "BILIM", practice: "AMALIYOT", outcome: "NATIJA", footer: "KATTA IMKONIYATLAR SARI", future: "HAR BIR QADAM YANADA YORQIN KELAJAKKA",
  loginHero: "Har kuni bir qadam", loginHeroGold: "oldinga.", loginHeroDescription: "Yangi bilimlar, katta imkoniyatlar — barchasi sizning qo‘lingizda.", loginQuote: "Bugungi sa’y-harakat — ertangi muvaffaqiyat.",
  loginTitle: "Gradexa’ga kirish", loginDescription: "Hisobingizga kirib, o‘qishni davom ettiring. Sizni yana ko‘rganimizdan xursandmiz!", email: "Email", emailPlaceholder: "Email manzilingiz", password: "Parol", passwordPlaceholder: "Parolingiz", forgot: "Parolni unutdingizmi?", signingIn: "Tekshirilmoqda…", protected: "Himoyalangan ulanish", privacy: "Ma’lumotlaringiz xavfsiz saqlanadi.", showPassword: "Parolni ko‘rsatish", hidePassword: "Parolni yashirish", capsLock: "Caps Lock yoqilgan",
  forgotTitle: "Parolni tiklash", forgotDescription: "Akkauntingiz email manzilini kiriting, biz sizga parolni tiklash havolasini yuboramiz.", sendLink: "Tiklash havolasini yuborish", sending: "Yuborilmoqda…", notice: "Akkaunt mavjud bo‘lsa, tiklash havolasi yuboriladi.", sentTitle: "Emailingizni tekshiring", sentDescription: "Agar hisob mavjud bo‘lsa, tiklash havolasi yuborildi. Spam papkasini ham tekshiring. Havolani shu brauzerda oching.", resend: "Havolani qayta yuborish", anotherEmail: "Boshqa email kiritish", wait: "Qayta yuborish", seconds: "soniya", opensDoors: "Bilim eshiklarni", opensDoorsGold: "ochadi",
  resetTitle: "Yangi parol o‘rnating", resetDescription: "Xavfsizligingiz uchun kuchli parol yarating. Parolingiz kamida 8 ta belgidan iborat bo‘lishi kerak.", newPassword: "Yangi parol", newPasswordPlaceholder: "Yangi parol kiriting", confirm: "Parolni tasdiqlang", confirmPlaceholder: "Parolni qayta kiriting", ruleLength: "Kamida 8 belgi", ruleCase: "Katta va kichik harf", ruleNumber: "Kamida bitta raqam", strength: "Parol kuchi", strengthEmpty: "", strengthWeak: "Zaif", strengthFair: "O‘rtacha", strengthGood: "Yaxshi", strengthStrong: "Kuchli", match: "Parollar mos", mismatch: "Parollar bir xil emas.", save: "Parolni saqlash", saving: "Saqlanmoqda…", strongPassword: "Kuchli parol —", secureFuture: "xavfsiz kelajak", resetFooter: "O‘Z MAQSADLARINGIZGA ISHONCH BILAN YURING", resetSuccess: "Yangi parol saqlandi", resetSuccessDescription: "Parolingiz yangilandi. Endi yangi parol bilan hisobingizga kiring.", expiredTitle: "Yangi havola kerak", expiredDescription: "Tiklash havolasi eskirgan yoki bu brauzerda tasdiqlanmagan. Yangisini so‘rab, emaildagi havolani shu brauzerda oching.", newLink: "Yangi havola olish", unavailableTitle: "Ulanishni tekshiring", unavailableDescription: "Hisobingizni hozir tekshira olmadik. Birozdan keyin sahifani qayta yuklang.", retry: "Qayta urinish", securityNote: "Parolni boshqa saytlarda ishlatmagan bo‘lishingiz tavsiya etiladi.",
};

type PublicCopy = { [K in keyof typeof uz]: string };
const en: PublicCopy = {
  language: "Choose language", courses: "Courses", how: "How it works", login: "Sign in", back: "Back to sign in", home: "Home",
  eyebrow: "TOWARDS NEW POSSIBILITIES", heroStart: "Take your knowledge", heroGold: "to the next level", heroEnd: ".", heroDescription: "Practical skills for modern careers, real projects and measurable results. Find a clearer path forward with Gradexa.", start: "Start learning", viewCourses: "Explore courses", video: "Video lessons", videoDescription: "Clear and practical", tests: "Practical quizzes", testsDescription: "Build your knowledge", results: "Results", resultsDescription: "Track your progress", quote: "Small steps lead to great results.", goal: "Towards your goal", goalDescription: "One step every day", popular: "Popular courses", allCourses: "View all courses", frontendDescription: "Learn the foundations of building modern web interfaces.", jsDescription: "Learn JavaScript from the basics to practical projects.", uiDescription: "Work with modern design systems and components.", frontendCategory: "Frontend", jsCategory: "Programming", uiCategory: "Design", beginner: "Beginner", intermediate: "Intermediate", learners: "learners", openCourse: "Open course", fourSteps: "New knowledge in 4 simple steps", step1: "Choose a course", step1Description: "Find the course that fits your goals.", step2: "Study the lessons", step2Description: "Learn step by step with video lessons.", step3: "Take practical quizzes", step3Description: "Put your knowledge into practice.", step4: "See your results", step4Description: "Move forward with new skills.", knowledge: "KNOWLEDGE", practice: "PRACTICE", outcome: "RESULTS", footer: "TOWARDS GREATER POSSIBILITIES", future: "EVERY STEP TOWARDS A BRIGHTER FUTURE",
  loginHero: "One step forward", loginHeroGold: "every day.", loginHeroDescription: "New knowledge and greater opportunities are in your hands.", loginQuote: "Today’s effort is tomorrow’s success.", loginTitle: "Sign in to Gradexa", loginDescription: "Sign in to continue learning. We’re glad to see you again!", email: "Email", emailPlaceholder: "Your email address", password: "Password", passwordPlaceholder: "Your password", forgot: "Forgot your password?", signingIn: "Signing in…", protected: "Protected connection", privacy: "Your information is stored securely.", showPassword: "Show password", hidePassword: "Hide password", capsLock: "Caps Lock is on",
  forgotTitle: "Reset your password", forgotDescription: "Enter your account email address and we’ll send you a password reset link.", sendLink: "Send reset link", sending: "Sending…", notice: "If an account exists, a reset link will be sent.", sentTitle: "Check your email", sentDescription: "If an account exists, a reset link has been sent. Check your spam folder too. Open the link in this browser.", resend: "Send link again", anotherEmail: "Use another email", wait: "Send again in", seconds: "seconds", opensDoors: "Knowledge opens", opensDoorsGold: "doors",
  resetTitle: "Set a new password", resetDescription: "Create a strong password to protect your account. Use at least 8 characters.", newPassword: "New password", newPasswordPlaceholder: "Enter a new password", confirm: "Confirm password", confirmPlaceholder: "Re-enter your password", ruleLength: "At least 8 characters", ruleCase: "Uppercase and lowercase letters", ruleNumber: "At least one number", strength: "Password strength", strengthEmpty: "", strengthWeak: "Weak", strengthFair: "Fair", strengthGood: "Good", strengthStrong: "Strong", match: "Passwords match", mismatch: "Passwords do not match.", save: "Save password", saving: "Saving…", strongPassword: "Strong password —", secureFuture: "a safer future", resetFooter: "MOVE TOWARDS YOUR GOALS WITH CONFIDENCE", resetSuccess: "New password saved", resetSuccessDescription: "Your password has been updated. Sign in with your new password.", expiredTitle: "You need a new link", expiredDescription: "This link has expired or could not be verified in this browser. Request a new link and open the email in this browser.", newLink: "Get a new link", unavailableTitle: "Check your connection", unavailableDescription: "We couldn’t verify your account right now. Try reloading the page shortly.", retry: "Try again", securityNote: "Choose a password you do not use on other websites.",
};
const ru: PublicCopy = {
  language: "Выбрать язык", courses: "Курсы", how: "Как это работает", login: "Войти", back: "Вернуться ко входу", home: "Главная",
  eyebrow: "К НОВЫМ ВОЗМОЖНОСТЯМ", heroStart: "Поднимите знания", heroGold: "на новый уровень", heroEnd: ".", heroDescription: "Практические навыки для современных профессий, реальные проекты и измеримые результаты. Двигайтесь вперёд вместе с Gradexa.", start: "Начать обучение", viewCourses: "Посмотреть курсы", video: "Видеоуроки", videoDescription: "Понятно и на практике", tests: "Практические тесты", testsDescription: "Закрепляйте знания", results: "Результаты", resultsDescription: "Следите за прогрессом", quote: "Маленькие шаги ведут к большим результатам.", goal: "На пути к цели", goalDescription: "Шаг вперёд каждый день", popular: "Популярные курсы", allCourses: "Все курсы", frontendDescription: "Изучите основы создания современных веб-интерфейсов.", jsDescription: "Освойте JavaScript от основ до практических проектов.", uiDescription: "Работайте с дизайн-системами и компонентами.", frontendCategory: "Фронтенд", jsCategory: "Программирование", uiCategory: "Дизайн", beginner: "Начальный", intermediate: "Средний", learners: "учеников", openCourse: "Открыть курс", fourSteps: "Новые знания за 4 простых шага", step1: "Выберите курс", step1Description: "Найдите курс под свои цели.", step2: "Изучайте уроки", step2Description: "Учитесь шаг за шагом с видеоуроками.", step3: "Пройдите тесты", step3Description: "Проверьте знания на практике.", step4: "Получите результат", step4Description: "Двигайтесь вперёд с новыми навыками.", knowledge: "ЗНАНИЯ", practice: "ПРАКТИКА", outcome: "РЕЗУЛЬТАТ", footer: "К БОЛЬШИМ ВОЗМОЖНОСТЯМ", future: "КАЖДЫЙ ШАГ — К ЯРКОМУ БУДУЩЕМУ",
  loginHero: "Каждый день —", loginHeroGold: "шаг вперёд.", loginHeroDescription: "Новые знания и большие возможности в ваших руках.", loginQuote: "Сегодняшние усилия — завтрашний успех.", loginTitle: "Вход в Gradexa", loginDescription: "Войдите в аккаунт и продолжайте учиться. Рады видеть вас снова!", email: "Email", emailPlaceholder: "Ваш email", password: "Пароль", passwordPlaceholder: "Ваш пароль", forgot: "Забыли пароль?", signingIn: "Проверяем…", protected: "Защищённое соединение", privacy: "Ваши данные надёжно хранятся.", showPassword: "Показать пароль", hidePassword: "Скрыть пароль", capsLock: "Включён Caps Lock",
  forgotTitle: "Восстановление пароля", forgotDescription: "Введите email аккаунта, и мы отправим ссылку для восстановления пароля.", sendLink: "Отправить ссылку", sending: "Отправляем…", notice: "Если аккаунт существует, ссылка будет отправлена.", sentTitle: "Проверьте почту", sentDescription: "Если аккаунт существует, ссылка отправлена. Проверьте также папку «Спам». Откройте ссылку в этом браузере.", resend: "Отправить повторно", anotherEmail: "Указать другой email", wait: "Повторная отправка через", seconds: "сек.", opensDoors: "Знания открывают", opensDoorsGold: "двери",
  resetTitle: "Задайте новый пароль", resetDescription: "Создайте надёжный пароль для защиты аккаунта. Используйте не менее 8 символов.", newPassword: "Новый пароль", newPasswordPlaceholder: "Введите новый пароль", confirm: "Подтвердите пароль", confirmPlaceholder: "Повторите пароль", ruleLength: "Не менее 8 символов", ruleCase: "Прописные и строчные буквы", ruleNumber: "Хотя бы одна цифра", strength: "Надёжность пароля", strengthEmpty: "", strengthWeak: "Слабый", strengthFair: "Средний", strengthGood: "Хороший", strengthStrong: "Надёжный", match: "Пароли совпадают", mismatch: "Пароли не совпадают.", save: "Сохранить пароль", saving: "Сохраняем…", strongPassword: "Надёжный пароль —", secureFuture: "безопасное будущее", resetFooter: "ДВИГАЙТЕСЬ К СВОИМ ЦЕЛЯМ УВЕРЕННО", resetSuccess: "Новый пароль сохранён", resetSuccessDescription: "Ваш пароль обновлён. Войдите в аккаунт с новым паролем.", expiredTitle: "Нужна новая ссылка", expiredDescription: "Ссылка устарела или не подтверждена в этом браузере. Запросите новую и откройте письмо в этом браузере.", newLink: "Получить новую ссылку", unavailableTitle: "Проверьте соединение", unavailableDescription: "Не удалось проверить аккаунт. Попробуйте обновить страницу немного позже.", retry: "Повторить", securityNote: "Используйте пароль, которого нет на других сайтах.",
};
export const publicCopy = { uz, en, ru };
